spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dairui123
    url: jdbc:mysql://localhost:3306/glgas?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
 dev
