spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    116.62.200.72:3306/lidayuan
    url:  jdbc:mysql://132.232.173.122:3306/gl_gas?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: dairui123
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  application:
    name: user 
  http:
    encoding:
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: false
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .html
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static/,classpath:/resources/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  redis:
    host: 132.232.173.122
    port: 6379
    password: dairui123
  rabbitmq:
    host: 132.232.173.122
    port: 5672
    username: guest
    password: guest
  application:
    name: provider
  messages:
    encoding: utf-8
server:
  port: 7878
  servlet:
    context-path: /glgas
mybatis:
  mapper-locations: classpath*:mapping/*.xml
uploadDir:
  image: /opt/javaapps/uploads/
